// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg4BAcktlsHj7wsKrQZnvit9RFlJv39QA',
    appId: '1:202675725142:web:c7eacaae25dbd42dca2cf7',
    messagingSenderId: '202675725142',
    projectId: 'sharephoto-2024',
    authDomain: 'sharephoto-2024.firebaseapp.com',
    storageBucket: 'sharephoto-2024.appspot.com',
    measurementId: 'G-5BKHSF1VXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdaNfA3vUy9o63NikU-ZJmTRZVx-gAkOU',
    appId: '1:202675725142:android:023d8c9215d2f9d4ca2cf7',
    messagingSenderId: '202675725142',
    projectId: 'sharephoto-2024',
    storageBucket: 'sharephoto-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxr3tmKHFCMBmvtlfDMNMv3f2CpDiSRpg',
    appId: '1:202675725142:ios:8ed399a6dccf6ac3ca2cf7',
    messagingSenderId: '202675725142',
    projectId: 'sharephoto-2024',
    storageBucket: 'sharephoto-2024.appspot.com',
    iosBundleId: 'com.example.photoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxr3tmKHFCMBmvtlfDMNMv3f2CpDiSRpg',
    appId: '1:202675725142:ios:8ed399a6dccf6ac3ca2cf7',
    messagingSenderId: '202675725142',
    projectId: 'sharephoto-2024',
    storageBucket: 'sharephoto-2024.appspot.com',
    iosBundleId: 'com.example.photoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg4BAcktlsHj7wsKrQZnvit9RFlJv39QA',
    appId: '1:202675725142:web:b70d0e0063c28c05ca2cf7',
    messagingSenderId: '202675725142',
    projectId: 'sharephoto-2024',
    authDomain: 'sharephoto-2024.firebaseapp.com',
    storageBucket: 'sharephoto-2024.appspot.com',
    measurementId: 'G-Q4CYCG73M9',
  );
}
